### ISSUE TITLE
Implement Menu

### ISSUE THREAD

**Issue by adityaponnada** [ideepakkrishnan/ideepakkrishnan.github.io#1]
We need to implement menu: Even bootstrap default will do (as long as it does not break the consistency)

Menu items:
1. Home
2. Points
3. Check-in
4. Events
5. Moments
6. My Settings

**Comment by deepchheda** [comment]
i do not know how to implement the menu in bootstrap. i just had mention it can be done

**Comment by adityaponnada** [comment]
Then finish other pages. We will look at it tomorrow. But try to finish
remaining pages. We are running out of time.

**Comment by adityaponnada** [comment]
you said you knew bootstrap! 
https://getbootstrap.com/components/#navbar

other teams were able to do it. I refuse to believe you can't build menu in bootstrap!
