### ISSUE TITLE
Implement SMS Notification Page

### ISSUE THREAD

**Issue by adityaponnada** [ideepakkrishnan/ideepakkrishnan.github.io#2]
page uploaded in the google drive.

A small red strip will appear on top once the "notify" button is clicked.

attached screenshot.
![sms_notif](https://cloud.githubusercontent.com/assets/16159941/11605222/42e43b12-9ac8-11e5-80cd-872ca9c5bd72.png)

**Comment by deepchheda** [comment]
making that needs javascript onclick or something. I have not idea how to do this

**Comment by adityaponnada** [comment]
Anything that you can build tonight? At least the moments page and all.

At least search online ... Or create a div for us to look at later.

**Comment by deepchheda** [comment]
i am making the settings page

**Comment by adityaponnada** [comment]
Again, moments, moments preview, profile settings, are to be completed.

**Comment by adityaponnada** [comment]
http://www.htmlcodetutorial.com/linking/linking_famsupp_70.html

https://www.youtube.com/watch?v=VnHvVz_bFKo

this has some useful info.
