### ISSUE TITLE
Implement Profile setting page 

### ISSUE THREAD

**Issue by adityaponnada** [ideepakkrishnan/ideepakkrishnan.github.io#3]
Implement the static page. Functionality is not our priority

Please find attached screenshot.
![profilesettings-01](https://cloud.githubusercontent.com/assets/16159941/11605482/adb41862-9ace-11e5-8fe5-73f4a4e312ca.jpg)

**Comment by deepchheda** [comment]
need images for customise text A A A..

**Comment by adityaponnada** [comment]
I'll provide in a while.

**Comment by adityaponnada** [comment]
Here are the assets: a
![ucb_onthemove](https://cloud.githubusercontent.com/assets/16159941/11612395/90a992e4-9bc6-11e5-8693-e220aecd2606.png)

![aa](https://cloud.githubusercontent.com/assets/16159941/11612396/96ae9428-9bc6-11e5-996e-d4658f39eed5.png)
![aaa](https://cloud.githubusercontent.com/assets/16159941/11612397/9b3cb934-9bc6-11e5-83da-1f60fdd8981b.png)
![aaaa](https://cloud.githubusercontent.com/assets/16159941/11612398/9ef85f38-9bc6-11e5-8097-eb2ca496de41.png)

**Comment by adityaponnada** [comment]
Added the assets
